// vocabulary.js

const vocabulary_test = [
	{ 
		0: { 
			title: 'Saudações e Expressões Básicas', 
			words: [
				{ kana: 'おはようございます', kanji: 'お早うございます', furigana: [{ position: 1, reading: 'はや' }], romaji: 'ohayou gozaimasu', meaning: 'Bom dia (formal)' },
				{ kana: 'おはよう', kanji: 'お早う', furigana: [{ position: 1, reading: 'はや' }], romaji: 'ohayou', meaning: 'Bom dia (informal)' }
			]
		}
	},
	{ 
		1: { 
			title: 'Pessoas e Família', 
			words: [
				{ kana: 'なまえ', kanji: '名前', furigana: [{ position: 0, reading: 'なまえ', length: 2 }], romaji: 'namae', meaning: 'Nome' },
				{ kana: 'わたし', kanji: '私', furigana: [{ position: 0, reading: 'わたし' }], romaji: 'watashi', meaning: 'Eu' },
			]
		}
	}
]

const vocabulary = [
    // === Saudações e Expressões Básicas ===
    { kana: 'おはようございます', kanji: 'お早うございます', furigana: [{ position: 1, reading: 'はや' }], romaji: 'ohayou gozaimasu', meaning: 'Bom dia (formal)' },
    { kana: 'おはよう', kanji: 'お早う', furigana: [{ position: 1, reading: 'はや' }], romaji: 'ohayou', meaning: 'Bom dia (informal)' },
    { kana: 'こんにちは', kanji: null, furigana: null, romaji: 'konnichiwa', meaning: 'Olá / Boa tarde' },
    { kana: 'こんばんは', kanji: '今晩は', furigana: [{ position: 0, reading: 'こん' }, { position: 1, reading: 'ばん' }], romaji: 'konbanwa', meaning: 'Boa noite (ao chegar)' },
    { kana: 'おやすみなさい', kanji: 'お休みなさい', furigana: [{ position: 1, reading: 'やす' }], romaji: 'oyasuminasai', meaning: 'Boa noite (ao se despedir/dormir)' },
    { kana: 'さようなら', kanji: null, furigana: null, romaji: 'sayounara', meaning: 'Adeus (formal/longa despedida)' },
    { kana: 'じゃあね', kanji: null, furigana: null, romaji: 'jaa ne', meaning: 'Até mais / Tchau (informal)' },
    { kana: 'またあした', kanji: 'また明日', furigana: [{ position: 2, reading: 'あした' }], romaji: 'mata ashita', meaning: 'Até amanhã' },
    { kana: 'ありがとう', kanji: null, furigana: null, romaji: 'arigatou', meaning: 'Obrigado(a) (informal)' },
    { kana: 'ありがとうございます', kanji: null, furigana: null, romaji: 'arigatou gozaimasu', meaning: 'Muito obrigado(a) (formal)' },
    { kana: 'どうも', kanji: null, furigana: null, romaji: 'doumo', meaning: 'Obrigado / Oi (muito informal)' },
    { kana: 'すみません', kanji: null, furigana: null, romaji: 'sumimasen', meaning: 'Com licença / Desculpe / Obrigado' },
    { kana: 'ごめんなさい', kanji: null, furigana: null, romaji: 'gomennasai', meaning: 'Me desculpe (mais pessoal)' },
    { kana: 'はい', kanji: null, furigana: null, romaji: 'hai', meaning: 'Sim' },
    { kana: 'いいえ', kanji: null, furigana: null, romaji: 'iie', meaning: 'Não' },
    { kana: 'おねがいします', kanji: 'お願いします', furigana: [{ position: 1, reading: 'ねが' }], romaji: 'onegaishimasu', meaning: 'Por favor' },
    { kana: 'どうぞ', kanji: null, furigana: null, romaji: 'douzo', meaning: 'Por favor / Pode ir / Sirva-se' },
    { kana: 'いただきます', kanji: '頂きます', furigana: [{ position: 0, reading: 'いただ' }], romaji: 'itadakimasu', meaning: 'Obrigado pela comida (antes de comer)' },
    { kana: 'ごちそうさまでした', kanji: 'ご馳走様でした', furigana: [{ position: 1, reading: 'ちそ' }, { position: 2, reading: 'う' }, { position: 3, reading: 'さま' }], romaji: 'gochisousama deshita', meaning: 'Obrigado pela comida (depois de comer)' },
    { kana: 'いってきます', kanji: '行ってきます', furigana: [{ position: 0, reading: 'い' }], romaji: 'ittekimasu', meaning: 'Estou indo (dito ao sair de casa)' },
    { kana: 'いってらっしゃい', kanji: '行ってらっしゃい', furigana: [{ position: 0, reading: 'い' }], romaji: 'itterasshai', meaning: 'Vá com cuidado (resposta para ittekimasu)' },
    { kana: 'ただいま', kanji: null, furigana: null, romaji: 'tadaima', meaning: 'Cheguei (dito ao voltar para casa)' },
    { kana: 'おかえりなさい', kanji: 'お帰りなさい', furigana: [{ position: 1, reading: 'かえ' }], romaji: 'okaerinasai', meaning: 'Bem-vindo(a) de volta (resposta para tadaima)' },
    { kana: 'はじめまして', kanji: '初めまして', furigana: [{ position: 0, reading: 'はじ' }], romaji: 'hajimemashite', meaning: 'Prazer em conhecê-lo (ao se apresentar)' },
    { kana: 'よろしくおねがいします', kanji: 'よろしくお願いします', furigana: [{ position: 0, reading: 'よろ' }, { position: 3, reading: 'お' }, { position: 4, reading: 'ね' }, { position: 5, reading: 'が' }], romaji: 'yoroshiku onegaishimasu', meaning: 'Prazer em conhecê-lo (final da apresentação) / Por favor, cuide de mim' },
    { kana: 'しつれいします', kanji: '失礼します', furigana: [{ position: 0, reading: 'しつ' }, { position: 1, reading: 'れい' }], romaji: 'shitsureishimasu', meaning: 'Com licença (ao entrar/sair) / Desculpe a indelicadeza' },
    { kana: 'おつかれさまでした', kanji: 'お疲れ様でした', furigana: [{ position: 1, reading: 'つか' }, { position: 3, reading: 'さま' }], romaji: 'otsukaresama deshita', meaning: 'Bom trabalho (após o trabalho/esforço)' },
    { kana: 'いらっしゃいませ', kanji: null, furigana: null, romaji: 'irasshaimase', meaning: 'Bem-vindo(a) (em lojas, restaurantes)' },
    { kana: 'おじゃまします', kanji: 'お邪魔します', furigana: [{ position: 1, reading: 'じゃ' }, { position: 2, reading: 'ま' }], romaji: 'ojamashimasu', meaning: 'Com licença (ao entrar na casa de alguém)' },
    { kana: 'おまたせしました', kanji: 'お待たせしました', furigana: [{ position: 1, reading: 'ま' }], romaji: 'omatase shimashita', meaning: 'Desculpe por fazê-lo esperar' },
    { kana: 'どういたしまして', kanji: null, furigana: null, romaji: 'dou itashimashite', meaning: 'De nada' },

    // === Pessoas e Família ===
    { kana: 'なまえ', kanji: '名前', furigana: [{ position: 0, reading: 'なまえ', length: 2 }], romaji: 'namae', meaning: 'Nome' },
    { kana: 'わたし', kanji: '私', furigana: [{ position: 0, reading: 'わたし' }], romaji: 'watashi', meaning: 'Eu' },
    { kana: 'ぼく', kanji: '僕', furigana: [{ position: 0, reading: 'ぼく' }], romaji: 'boku', meaning: 'Eu (masculino, informal)' },
    { kana: 'あなた', kanji: '貴方', furigana: [{ position: 0, reading: 'あな' }, { position: 1, reading: 'た' }], romaji: 'anata', meaning: 'Você' },
    { kana: 'かれ', kanji: '彼', furigana: [{ position: 0, reading: 'かれ' }], romaji: 'kare', meaning: 'Ele / Namorado' },
    { kana: 'かのじょ', kanji: '彼女', furigana: [{ position: 0, reading: 'かのじょ', length: 2 }], romaji: 'kanojo', meaning: 'Ela / Namorada' },
    { kana: 'ひと', kanji: '人', furigana: [{ position: 0, reading: 'ひと' }], romaji: 'hito', meaning: 'Pessoa' },
    { kana: 'ともだち', kanji: '友達', furigana: [{ position: 0, reading: 'ともだち', length: 2 }], romaji: 'tomodachi', meaning: 'Amigo(a)' },
    { kana: 'かぞく', kanji: '家族', furigana: [{ position: 0, reading: 'かぞく', length: 2 }], romaji: 'kazoku', meaning: 'Família' },
    { kana: 'おとうさん', kanji: 'お父さん', furigana: [{ position: 1, reading: 'とう' }], romaji: 'otousan', meaning: 'Pai (de outra pessoa ou formal)' },
    { kana: 'ちち', kanji: '父', furigana: [{ position: 0, reading: 'ちち' }], romaji: 'chichi', meaning: 'Meu pai' },
    { kana: 'おかあさん', kanji: 'お母さん', furigana: [{ position: 1, reading: 'かあ' }], romaji: 'okaasan', meaning: 'Mãe (de outra pessoa ou formal)' },
    { kana: 'はは', kanji: '母', furigana: [{ position: 0, reading: 'はは' }], romaji: 'haha', meaning: 'Minha mãe' },
    { kana: 'こども', kanji: '子供', furigana: [{ position: 0, reading: 'こども', length: 2 }], romaji: 'kodomo', meaning: 'Criança / Filho(a)' },
    { kana: 'おとこのひと', kanji: '男の人', furigana: [{ position: 0, reading: 'おとこ' }, { position: 2, reading: 'ひと' }], romaji: 'otoko no hito', meaning: 'Homem' },
    { kana: 'おんなのひと', kanji: '女の人', furigana: [{ position: 0, reading: 'おんな' }, { position: 2, reading: 'ひと' }], romaji: 'onna no hito', meaning: 'Mulher' },
    { kana: 'おとこのこ', kanji: '男の子', furigana: [{ position: 0, reading: 'おとこ' }, { position: 2, reading: 'こ' }], romaji: 'otokonoko', meaning: 'Menino' },
    { kana: 'おんなのこ', kanji: '女の子', furigana: [{ position: 0, reading: 'おんな' }, { position: 2, reading: 'こ' }], romaji: 'onnanoko', meaning: 'Menina' },
    { kana: 'きょうだい', kanji: '兄弟', furigana: [{ position: 0, reading: 'きょう' }, { position: 1, reading: 'だい' }], romaji: 'kyoudai', meaning: 'Irmãos' },
    { kana: 'あに', kanji: '兄', furigana: [{ position: 0, reading: 'あに' }], romaji: 'ani', meaning: 'Meu irmão mais velho' },
    { kana: 'おにいさん', kanji: 'お兄さん', furigana: [{ position: 1, reading: 'にい' }], romaji: 'oniisan', meaning: 'Irmão mais velho (de outra pessoa ou formal)' },
    { kana: 'あね', kanji: '姉', furigana: [{ position: 0, reading: 'あね' }], romaji: 'ane', meaning: 'Minha irmã mais velha' },
    { kana: 'おねえさん', kanji: 'お姉さん', furigana: [{ position: 1, reading: 'ねえ' }], romaji: 'oneesan', meaning: 'Irmã mais velha (de outra pessoa ou formal)' },
    { kana: 'おとうと', kanji: '弟', furigana: [{ position: 0, reading: 'おとうと' }], romaji: 'otouto', meaning: 'Meu irmão mais novo' },
    { kana: 'いもうと', kanji: '妹', furigana: [{ position: 0, reading: 'いもうと' }], romaji: 'imouto', meaning: 'Minha irmã mais nova' },
    { kana: 'おじいさん', kanji: 'お祖父さん', furigana: [{ position: 1, reading: 'じい' }], romaji: 'ojiisan', meaning: 'Avô (de outro ou formal)' },
    { kana: 'そふ', kanji: '祖父', furigana: [{ position: 0, reading: 'そ' }, { position: 1, reading: 'ふ' }], romaji: 'sofu', meaning: 'Meu avô' },
    { kana: 'おばあさん', kanji: 'お祖母さん', furigana: [{ position: 1, reading: 'ばあ' }], romaji: 'obaasan', meaning: 'Avó (de outra ou formal)' },
    { kana: 'そぼ', kanji: '祖母', furigana: [{ position: 0, reading: 'そ' }, { position: 1, reading: 'ぼ' }], romaji: 'sobo', meaning: 'Minha avó' },

    // === Profissões ===
    { kana: 'せんせい', kanji: '先生', furigana: [{ position: 0, reading: 'せん' }, { position: 1, reading: 'せい' }], romaji: 'sensei', meaning: 'Professor(a) / Mestre' },
    { kana: 'がくせい', kanji: '学生', furigana: [{ position: 0, reading: 'がく' }, { position: 1, reading: 'せい' }], romaji: 'gakusei', meaning: 'Estudante' },
    { kana: 'かいしゃいん', kanji: '会社員', furigana: [{ position: 0, reading: 'かい' }, { position: 1, reading: 'しゃ' }, { position: 2, reading: 'いん' }], romaji: 'kaishain', meaning: 'Funcionário de empresa' },
    { kana: 'いしゃ', kanji: '医者', furigana: [{ position: 0, reading: 'い' }, { position: 1, reading: 'しゃ' }], romaji: 'isha', meaning: 'Médico(a)' },
    { kana: 'べんごし', kanji: '弁護士', furigana: [{ position: 0, reading: 'べん' }, { position: 1, reading: 'ご' }, { position: 2, reading: 'し' }], romaji: 'bengoshi', meaning: 'Advogado(a)' },

    // === Comida e Bebida ===
    { kana: 'たべもの', kanji: '食べ物', furigana: [{ position: 0, reading: 'た' }, { position: 2, reading: 'もの' }], romaji: 'tabemono', meaning: 'Comida' },
    { kana: 'のみもの', kanji: '飲み物', furigana: [{ position: 0, reading: 'の' }, { position: 2, reading: 'もの' }], romaji: 'nomimono', meaning: 'Bebida' },
    { kana: 'みず', kanji: '水', furigana: [{ position: 0, reading: 'みず' }], romaji: 'mizu', meaning: 'Água' },
    { kana: 'ごはん', kanji: 'ご飯', furigana: [{ position: 1, reading: 'はん' }], romaji: 'gohan', meaning: 'Arroz / Refeição' },
    { kana: 'めし', kanji: '飯', furigana: [{ position: 0, reading: 'めし' }], romaji: 'meshi', meaning: 'Refeição / Arroz (gíria, informal)' },
    { kana: 'パン', kanji: null, furigana: null, romaji: 'pan', meaning: 'Pão' },
    { kana: 'にく', kanji: '肉', furigana: [{ position: 0, reading: 'にく' }], romaji: 'niku', meaning: 'Carne' },
    { kana: 'さかな', kanji: '魚', furigana: [{ position: 0, reading: 'さかな' }], romaji: 'sakana', meaning: 'Peixe' },
    { kana: 'やさい', kanji: '野菜', furigana: [{ position: 0, reading: 'や' }, { position: 1, reading: 'さい' }], romaji: 'yasai', meaning: 'Verduras / Legumes' },
    { kana: 'くだもの', kanji: '果物', furigana: [{ position: 0, reading: 'くだ' }, { position: 1, reading: 'もの' }], romaji: 'kudamono', meaning: 'Fruta' },
    { kana: 'りんご', kanji: '林檎', furigana: [{ position: 0, reading: 'りん' }, { position: 1, reading: 'ご' }], romaji: 'ringo', meaning: 'Maçã' },
    { kana: 'たまご', kanji: '卵', furigana: [{ position: 0, reading: 'たまご' }], romaji: 'tamago', meaning: 'Ovo' },
    { kana: 'おちゃ', kanji: 'お茶', furigana: [{ position: 1, reading: 'ちゃ' }], romaji: 'ocha', meaning: 'Chá' },
    { kana: 'コーヒー', kanji: null, furigana: null, romaji: 'koohii', meaning: 'Café (bebida)' },
    { kana: 'ぎゅうにゅう', kanji: '牛乳', furigana: [{ position: 0, reading: 'ぎゅう' }, { position: 1, reading: 'にゅう' }], romaji: 'gyuunyuu', meaning: 'Leite' },
    { kana: 'ビール', kanji: null, furigana: null, romaji: 'biiru', meaning: 'Cerveja' },
    { kana: 'さけ', kanji: '酒', furigana: [{ position: 0, reading: 'さけ' }], romaji: 'sake', meaning: 'Bebida alcoólica / Saquê' },
    { kana: 'りょうり', kanji: '料理', furigana: [{ position: 0, reading: 'りょう' }, { position: 1, reading: 'り' }], romaji: 'ryouri', meaning: 'Culinária / Prato' },
    { kana: 'さとう', kanji: '砂糖', furigana: [{ position: 0, reading: 'さ' }, { position: 1, reading: 'とう' }], romaji: 'satou', meaning: 'Açúcar' },
    { kana: 'しお', kanji: '塩', furigana: [{ position: 0, reading: 'しお' }], romaji: 'shio', meaning: 'Sal' },
    { kana: 'ラーメン', kanji: null, furigana: null, romaji: 'raamen', meaning: 'Ramen' },
    { kana: 'すし', kanji: '寿司', furigana: [{ position: 0, reading: 'す' }, { position: 1, reading: 'し' }], romaji: 'sushi', meaning: 'Sushi' },
    { kana: 'おかし', kanji: 'お菓子', furigana: [{ position: 1, reading: 'かし' }], romaji: 'okashi', meaning: 'Doce / Guloseima' },
    { kana: 'あさごはん', kanji: '朝ご飯', furigana: [{ position: 0, reading: 'あさ' }, { position: 2, reading: 'はん' }], romaji: 'asagohan', meaning: 'Café da manhã' },
    { kana: 'ひるごはん', kanji: '昼ご飯', furigana: [{ position: 0, reading: 'ひる' }, { position: 2, reading: 'はん' }], romaji: 'hirugohan', meaning: 'Almoço' },
    { kana: 'ばんごはん', kanji: '晩ご飯', furigana: [{ position: 0, reading: 'ばん' }, { position: 2, reading: 'はん' }], romaji: 'bangohan', meaning: 'Jantar' },

    // === Utensílios de Cozinha e Mesa ===
    { kana: 'しょっき', kanji: '食器', furigana: [{ position: 0, reading: 'しょっ' }, { position: 1, reading: 'き' }], romaji: 'shokki', meaning: 'Louça / Utensílios de mesa' },
    { kana: 'コップ', kanji: null, furigana: null, romaji: 'koppu', meaning: 'Copo' },
    { kana: 'さら', kanji: '皿', furigana: [{ position: 0, reading: 'さら' }], romaji: 'sara', meaning: 'Prato' },
    { kana: 'ちゃわん', kanji: '茶碗', furigana: [{ position: 0, reading: 'ちゃ' }, { position: 1, reading: 'わん' }], romaji: 'chawan', meaning: 'Tigela (para arroz)' },
    { kana: 'はし', kanji: '箸', furigana: [{ position: 0, reading: 'はし' }], romaji: 'hashi', meaning: 'Pauzinhos (hashi)' },
    { kana: 'スプーン', kanji: null, furigana: null, romaji: 'supuun', meaning: 'Colher' },
    { kana: 'フォーク', kanji: null, furigana: null, romaji: 'fooku', meaning: 'Garfo' },
    { kana: 'ナイフ', kanji: null, furigana: null, romaji: 'naifu', meaning: 'Faca' },
    { kana: 'れいぞうこ', kanji: '冷蔵庫', furigana: [{ position: 0, reading: 'れい' }, { position: 1, reading: 'ぞう' }, { position: 2, reading: 'こ' }], romaji: 'reizouko', meaning: 'Geladeira' },
    { kana: 'なべ', kanji: '鍋', furigana: [{ position: 0, reading: 'なべ' }], romaji: 'nabe', meaning: 'Panela' },

    // === Lugares ===
    { kana: 'いえ', kanji: '家', furigana: [{ position: 0, reading: 'いえ' }], romaji: 'ie', meaning: 'Casa' },
    { kana: 'うち', kanji: '家', furigana: [{ position: 0, reading: 'うち' }], romaji: 'uchi', meaning: 'Casa / Meu lar' },
    { kana: 'へや', kanji: '部屋', furigana: [{ position: 0, reading: 'へや' }], romaji: 'heya', meaning: 'Quarto / Cômodo' },
    { kana: 'だいどころ', kanji: '台所', furigana: [{ position: 0, reading: 'だい' }, { position: 1, reading: 'どころ' }], romaji: 'daidokoro', meaning: 'Cozinha' },
    { kana: 'トイレ', kanji: null, furigana: null, romaji: 'toire', meaning: 'Banheiro' },
    { kana: 'おふろ', kanji: 'お風呂', furigana: [{ position: 1, reading: 'ふろ' }], romaji: 'ofuro', meaning: 'Banheiro / Banheira' },
    { kana: 'がっこう', kanji: '学校', furigana: [{ position: 0, reading: 'がっ' }, { position: 1, reading: 'こう' }], romaji: 'gakkou', meaning: 'Escola' },
    { kana: 'だいがく', kanji: '大学', furigana: [{ position: 0, reading: 'だい' }, { position: 1, reading: 'がく' }], romaji: 'daigaku', meaning: 'Universidade' },
    { kana: 'としょかん', kanji: '図書館', furigana: [{ position: 0, reading: 'と' }, { position: 1, reading: 'しょ' }, { position: 2, reading: 'かん' }], romaji: 'toshokan', meaning: 'Biblioteca' },
    { kana: 'かいしゃ', kanji: '会社', furigana: [{ position: 0, reading: 'かい' }, { position: 1, reading: 'しゃ' }], romaji: 'kaisha', meaning: 'Empresa' },
    { kana: 'みせ', kanji: '店', furigana: [{ position: 0, reading: 'みせ' }], romaji: 'mise', meaning: 'Loja' },
    { kana: 'デパート', kanji: null, furigana: null, romaji: 'depaato', meaning: 'Loja de departamentos' },
    { kana: 'コンビニ', kanji: null, furigana: null, romaji: 'konbini', meaning: 'Loja de conveniência' },
    { kana: 'レストラン', kanji: null, furigana: null, romaji: 'resutoran', meaning: 'Restaurante' },
    { kana: 'えき', kanji: '駅', furigana: [{ position: 0, reading: 'えき' }], romaji: 'eki', meaning: 'Estação (de trem)' },
    { kana: 'ぎんこう', kanji: '銀行', furigana: [{ position: 0, reading: 'ぎん' }, { position: 1, reading: 'こう' }], romaji: 'ginkou', meaning: 'Banco' },
    { kana: 'びょういん', kanji: '病院', furigana: [{ position: 0, reading: 'びょう' }, { position: 1, reading: 'いん' }], romaji: 'byouin', meaning: 'Hospital' },
    { kana: 'こうえん', kanji: '公園', furigana: [{ position: 0, reading: 'こう' }, { position: 1, reading: 'えん' }], romaji: 'kouen', meaning: 'Parque' },
    { kana: 'くうこう', kanji: '空港', furigana: [{ position: 0, reading: 'くう' }, { position: 1, reading: 'こう' }], romaji: 'kuukou', meaning: 'Aeroporto' },
    { kana: 'ゆうびんきょく', kanji: '郵便局', furigana: [{ position: 0, reading: 'ゆう' }, { position: 1, reading: 'びん' }, { position: 2, reading: 'きょく' }], romaji: 'yuubinkyoku', meaning: 'Correios' },
    { kana: 'えいがかん', kanji: '映画館', furigana: [{ position: 0, reading: 'えい' }, { position: 1, reading: 'が' }, { position: 2, reading: 'かん' }], romaji: 'eigakan', meaning: 'Cinema' },
    { kana: 'たいしかん', kanji: '大使館', furigana: [{ position: 0, reading: 'たい' }, { position: 1, reading: 'し' }, { position: 2, reading: 'かん' }], romaji: 'taishikan', meaning: 'Embaixada' },
    { kana: 'まち', kanji: '町', furigana: [{ position: 0, reading: 'まち' }], romaji: 'machi', meaning: 'Cidade / Bairro' },

    // === Países ===
    { kana: 'くに', kanji: '国', furigana: [{ position: 0, reading: 'くに' }], romaji: 'kuni', meaning: 'País' },
    { kana: 'にほん', kanji: '日本', furigana: [{ position: 0, reading: 'に' }, { position: 1, reading: 'ほん' }], romaji: 'nihon', meaning: 'Japão' },
    { kana: 'とうきょう', kanji: '東京', furigana: [{ position: 0, reading: 'とう' }, { position: 1, reading: 'きょう' }], romaji: 'toukyou', meaning: 'Tóquio' },
    { kana: 'アメリカ', kanji: null, furigana: null, romaji: 'amerika', meaning: 'Estados Unidos' },
    { kana: 'ブラジル', kanji: null, furigana: null, romaji: 'burajiru', meaning: 'Brasil' },
    { kana: 'かんこく', kanji: '韓国', furigana: [{ position: 0, reading: 'かん' }, { position: 1, reading: 'こく' }], romaji: 'kankoku', meaning: 'Coreia do Sul' },
    { kana: 'ちゅうごく', kanji: '中国', furigana: [{ position: 0, reading: 'ちゅう' }, { position: 1, reading: 'ごく' }], romaji: 'chuugoku', meaning: 'China' },
    { kana: 'イギリス', kanji: null, furigana: null, romaji: 'igirisu', meaning: 'Reino Unido / Inglaterra' },
    { kana: 'フランス', kanji: null, furigana: null, romaji: 'furansu', meaning: 'França' },
    { kana: 'ドイツ', kanji: null, furigana: null, romaji: 'doitsu', meaning: 'Alemanha' },
    { kana: 'ポルトガル', kanji: null, furigana: null, romaji: 'porutogaru', meaning: 'Portugal' },

    // === Línguas e Nacionalidades ===
    { kana: 'にほんご', kanji: '日本語', furigana: [{ position: 0, reading: 'にほん' }, { position: 1, reading: 'ご' }], romaji: 'nihongo', meaning: 'Língua Japonesa' },
    { kana: 'えいご', kanji: '英語', furigana: [{ position: 0, reading: 'えい' }, { position: 1, reading: 'ご' }], romaji: 'eigo', meaning: 'Língua Inglesa' },
    { kana: 'ポルトガルご', kanji: 'ポルトガル語', furigana: [{ position: 5, reading: 'ご' }], romaji: 'porutogarugo', meaning: 'Língua Portuguesa' },
    { kana: 'がいこくご', kanji: '外国語', furigana: [{ position: 0, reading: 'がい' }, { position: 1, reading: 'こく' }, { position: 2, reading: 'ご' }], romaji: 'gaikokugo', meaning: 'Língua Estrangeira' },
    { kana: 'にほんじん', kanji: '日本人', furigana: [{ position: 0, reading: 'にほん' }, { position: 1, reading: 'じん' }], romaji: 'nihonjin', meaning: 'Japonês (nacionalidade)' },
    { kana: 'がいこくじん', kanji: '外国人', furigana: [{ position: 0, reading: 'がい' }, { position: 1, reading: 'こく' }, { position: 2, reading: 'じん' }], romaji: 'gaikokujin', meaning: 'Estrangeiro (nacionalidade)' },
    { kana: 'アメリカじん', kanji: 'アメリカ人', furigana: [{ position: 4, reading: 'じん' }], romaji: 'amerikajin', meaning: 'Americano (nacionalidade)' },

    // === Tempo e Calendário ===
    { kana: 'いま', kanji: '今', furigana: [{ position: 0, reading: 'いま' }], romaji: 'ima', meaning: 'Agora' },
    { kana: 'じかん', kanji: '時間', furigana: [{ position: 0, reading: 'じ' }, { position: 1, reading: 'かん' }], romaji: 'jikan', meaning: 'Tempo / Hora' },
    { kana: 'きょう', kanji: '今日', furigana: [{ position: 0, reading: 'きょ' }, { position: 1, reading: 'う' }], romaji: 'kyou', meaning: 'Hoje' },
    { kana: 'きのう', kanji: '昨日', furigana: [{ position: 0, reading: 'きのう' }], romaji: 'kinou', meaning: 'Ontem' },
    { kana: 'あした', kanji: '明日', furigana: [{ position: 0, reading: 'あ' }, { position: 1, reading: 'した' }], romaji: 'ashita', meaning: 'Amanhã' },
    { kana: 'あさって', kanji: '明後日', furigana: [{ position: 0, reading: 'あさっ' }, { position: 1, reading: 'て' }], romaji: 'asatte', meaning: 'Depois de amanhã' },
    { kana: 'おととい', kanji: '一昨日', furigana: [{ position: 0, reading: 'おととい' }], romaji: 'ototoi', meaning: 'Anteontem' },
    { kana: 'あさ', kanji: '朝', furigana: [{ position: 0, reading: 'あさ' }], romaji: 'asa', meaning: 'Manhã' },
    { kana: 'けさ', kanji: '今朝', furigana: [{ position: 0, reading: 'け' }, { position: 1, reading: 'さ' }], romaji: 'kesa', meaning: 'Esta manhã' },
    { kana: 'ひる', kanji: '昼', furigana: [{ position: 0, reading: 'ひる' }], romaji: 'hiru', meaning: 'Meio-dia / Tarde' },
    { kana: 'ゆうがた', kanji: '夕方', furigana: [{ position: 0, reading: 'ゆう' }, { position: 1, reading: 'がた' }], romaji: 'yuugata', meaning: 'Entardecer' },
    { kana: 'よる', kanji: '夜', furigana: [{ position: 0, reading: 'よる' }], romaji: 'yoru', meaning: 'Noite' },
    { kana: 'こんばん', kanji: '今晩', furigana: [{ position: 0, reading: 'こん' }, { position: 1, reading: 'ばん' }], romaji: 'konban', meaning: 'Esta noite' },
    { kana: 'しゅう', kanji: '週', furigana: [{ position: 0, reading: 'しゅう' }], romaji: 'shuu', meaning: 'Semana' },
    { kana: 'こんしゅう', kanji: '今週', furigana: [{ position: 0, reading: 'こん' }, { position: 1, reading: 'しゅう' }], romaji: 'konshuu', meaning: 'Esta semana' },
    { kana: 'せんしゅう', kanji: '先週', furigana: [{ position: 0, reading: 'せん' }, { position: 1, reading: 'しゅう' }], romaji: 'senshuu', meaning: 'Semana passada' },
    { kana: 'らいしゅう', kanji: '来週', furigana: [{ position: 0, reading: 'らい' }, { position: 1, reading: 'しゅう' }], romaji: 'raishuu', meaning: 'Próxima semana' },
    { kana: 'しゅうまつ', kanji: '週末', furigana: [{ position: 0, reading: 'しゅう' }, { position: 1, reading: 'まつ' }], romaji: 'shuumatsu', meaning: 'Fim de semana' },
    { kana: 'げつようび', kanji: '月曜日', furigana: [{ position: 0, reading: 'げつ' }, { position: 1, reading: 'よう' }, { position: 2, reading: 'び' }], romaji: 'getsuyoubi', meaning: 'Segunda-feira' },
    { kana: 'かようび', kanji: '火曜日', furigana: [{ position: 0, reading: 'か' }, { position: 1, reading: 'よう' }, { position: 2, reading: 'び' }], romaji: 'kayoubi', meaning: 'Terça-feira' },
    { kana: 'すいようび', kanji: '水曜日', furigana: [{ position: 0, reading: 'すい' }, { position: 1, reading: 'よう' }, { position: 2, reading: 'び' }], romaji: 'suiyoubi', meaning: 'Quarta-feira' },
    { kana: 'もくようび', kanji: '木曜日', furigana: [{ position: 0, reading: 'もく' }, { position: 1, reading: 'よう' }, { position: 2, reading: 'び' }], romaji: 'mokuyoubi', meaning: 'Quinta-feira' },
    { kana: 'きんようび', kanji: '金曜日', furigana: [{ position: 0, reading: 'きん' }, { position: 1, reading: 'よう' }, { position: 2, reading: 'び' }], romaji: 'kinyoubi', meaning: 'Sexta-feira' },
    { kana: 'どようび', kanji: '土曜日', furigana: [{ position: 0, reading: 'ど' }, { position: 1, reading: 'よう' }, { position: 2, reading: 'び' }], romaji: 'doyoubi', meaning: 'Sábado' },
    { kana: 'にちようび', kanji: '日曜日', furigana: [{ position: 0, reading: 'にち' }, { position: 1, reading: 'よう' }, { position: 2, reading: 'び' }], romaji: 'nichiyoubi', meaning: 'Domingo' },
    { kana: 'つき', kanji: '月', furigana: [{ position: 0, reading: 'つき' }], romaji: 'tsuki', meaning: 'Mês' },
    { kana: 'とし', kanji: '年', furigana: [{ position: 0, reading: 'とし' }], romaji: 'toshi', meaning: 'Ano' },
    { kana: 'ことし', kanji: '今年', furigana: [{ position: 0, reading: 'ことし' }], romaji: 'kotoshi', meaning: 'Este ano' },
    { kana: 'きょねん', kanji: '去年', furigana: [{ position: 0, reading: 'きょ' }, { position: 1, reading: 'ねん' }], romaji: 'kyonen', meaning: 'Ano passado' },
    { kana: 'らいねん', kanji: '来年', furigana: [{ position: 0, reading: 'らい' }, { position: 1, reading: 'ねん' }], romaji: 'rainen', meaning: 'Próximo ano' },
    { kana: 'たんじょうび', kanji: '誕生日', furigana: [{ position: 0, reading: 'たん' }, { position: 1, reading: 'じょう' }, { position: 2, reading: 'び' }], romaji: 'tanjoubi', meaning: 'Aniversário' },
    { kana: 'はる', kanji: '春', furigana: [{ position: 0, reading: 'はる' }], romaji: 'haru', meaning: 'Primavera' },
    { kana: 'なつ', kanji: '夏', furigana: [{ position: 0, reading: 'なつ' }], romaji: 'natsu', meaning: 'Verão' },
    { kana: 'あき', kanji: '秋', furigana: [{ position: 0, reading: 'あき' }], romaji: 'aki', meaning: 'Outono' },
    { kana: 'ふゆ', kanji: '冬', furigana: [{ position: 0, reading: 'ふゆ' }], romaji: 'fuyu', meaning: 'Inverno' },

	// === Natureza e Clima ===
	{ kana: 'てんき', kanji: '天気', furigana: [{ position: 0, reading: 'てん' }, { position: 1, reading: 'き' }], romaji: 'tenki', meaning: 'Tempo / Clima' },
	{ kana: 'せかい', kanji: '世界', furigana: [{ position: 0, reading: 'せ' }, { position: 1, reading: 'かい' }], romaji: 'sekai', meaning: 'Mundo' },
	{ kana: 'そら', kanji: '空', furigana: [{ position: 0, reading: 'そら' }], romaji: 'sora', meaning: 'Céu' },
	{ kana: 'たいよう', kanji: '太陽', furigana: [{ position: 0, reading: 'たい' }, { position: 1, reading: 'よう' }], romaji: 'taiyou', meaning: 'Sol' },
	{ kana: 'つき', kanji: '月', furigana: [{ position: 0, reading: 'つき' }], romaji: 'tsuki', meaning: 'Lua' },
	{ kana: 'ほし', kanji: '星', furigana: [{ position: 0, reading: 'ほし' }], romaji: 'hoshi', meaning: 'Estrela' },
	{ kana: 'ひ', kanji: '火', furigana: [{ position: 0, reading: 'ひ' }], romaji: 'hi', meaning: 'Fogo' },
	{ kana: 'あめ', kanji: '雨', furigana: [{ position: 0, reading: 'あめ' }], romaji: 'ame', meaning: 'Chuva' },
	{ kana: 'ゆき', kanji: '雪', furigana: [{ position: 0, reading: 'ゆき' }], romaji: 'yuki', meaning: 'Neve' },
	{ kana: 'かぜ', kanji: '風', furigana: [{ position: 0, reading: 'かぜ' }], romaji: 'kaze', meaning: 'Vento' },
	{ kana: 'くも', kanji: '雲', furigana: [{ position: 0, reading: 'くも' }], romaji: 'kumo', meaning: 'Nuvem' },
	{ kana: 'やま', kanji: '山', furigana: [{ position: 0, reading: 'やま' }], romaji: 'yama', meaning: 'Montanha' },
	{ kana: 'かざん', kanji: '火山', furigana: [{ position: 0, reading: 'か' }, { position: 1, reading: 'ざん' }], romaji: 'kazan', meaning: 'Vulcão' },
	{ kana: 'かわ', kanji: '川', furigana: [{ position: 0, reading: 'かわ' }], romaji: 'kawa', meaning: 'Rio' },
	{ kana: 'うみ', kanji: '海', furigana: [{ position: 0, reading: 'うみ' }], romaji: 'umi', meaning: 'Mar / Oceano' },
	{ kana: 'なみ', kanji: '波', furigana: [{ position: 0, reading: 'なみ' }], romaji: 'nami', meaning: 'Onda' },
	{ kana: 'つなみ', kanji: '津波', furigana: [{ position: 0, reading: 'つ' }, { position: 1, reading: 'なみ' }], romaji: 'tsunami', meaning: 'Tsunami / Maremoto' },
	{ kana: 'き', kanji: '木', furigana: [{ position: 0, reading: 'き' }], romaji: 'ki', meaning: 'Árvore' },
	{ kana: 'じしん', kanji: '地震', furigana: [{ position: 0, reading: 'じ' }, { position: 1, reading: 'しん' }], romaji: 'jishin', meaning: 'Terremoto' },

    // === Objetos Comuns ===
    { kana: 'もの', kanji: '物', furigana: [{ position: 0, reading: 'もの' }], romaji: 'mono', meaning: 'Coisa / Objeto' },
    { kana: 'つくえ', kanji: '机', furigana: [{ position: 0, reading: 'つくえ' }], romaji: 'tsukue', meaning: 'Mesa' },
    { kana: 'いす', kanji: '椅子', furigana: [{ position: 0, reading: 'い' }, { position: 1, reading: 'す' }], romaji: 'isu', meaning: 'Cadeira' },
    { kana: 'かばん', kanji: '鞄', furigana: [{ position: 0, reading: 'かばん' }], romaji: 'kaban', meaning: 'Bolsa / Mala' },
    { kana: 'かさ', kanji: '傘', furigana: [{ position: 0, reading: 'かさ' }], romaji: 'kasa', meaning: 'Guarda-chuva' },
    { kana: 'くつ', kanji: '靴', furigana: [{ position: 0, reading: 'くつ' }], romaji: 'kutsu', meaning: 'Sapatos' },
    { kana: 'おかね', kanji: 'お金', furigana: [{ position: 1, reading: 'かね' }], romaji: 'okane', meaning: 'Dinheiro' },
    { kana: 'とけい', kanji: '時計', furigana: [{ position: 0, reading: 'と' }, { position: 1, reading: 'けい' }], romaji: 'tokei', meaning: 'Relógio' },
    { kana: 'かみ', kanji: '紙', furigana: [{ position: 0, reading: 'かみ' }], romaji: 'kami', meaning: 'Papel' },
    { kana: 'かぎ', kanji: '鍵', furigana: [{ position: 0, reading: 'かぎ' }], romaji: 'kagi', meaning: 'Chave' },
    { kana: 'ドア', kanji: null, furigana: null, romaji: 'doa', meaning: 'Porta' },
    { kana: 'まど', kanji: '窓', furigana: [{ position: 0, reading: 'まど' }], romaji: 'mado', meaning: 'Janela' },
    { kana: 'でんき', kanji: '電気', furigana: [{ position: 0, reading: 'でん' }, { position: 1, reading: 'き' }], romaji: 'denki', meaning: 'Eletricidade / Luz' },
    { kana: 'はな', kanji: '花', furigana: [{ position: 0, reading: 'はな' }], romaji: 'hana', meaning: 'Flor' },
    { kana: 'しゃしん', kanji: '写真', furigana: [{ position: 0, reading: 'しゃ' }, { position: 1, reading: 'しん' }], romaji: 'shashin', meaning: 'Fotografia' },

    // === Demonstrativos ===
    { kana: 'これ', kanji: null, furigana: null, romaji: 'kore', meaning: 'Isto (perto de quem fala)' },
    { kana: 'それ', kanji: null, furigana: null, romaji: 'sore', meaning: 'Isso (perto de quem ouve)' },
    { kana: 'あれ', kanji: null, furigana: null, romaji: 'are', meaning: 'Aquilo (longe de ambos)' },
    { kana: 'この', kanji: null, furigana: null, romaji: 'kono', meaning: 'Este / Esta (+ substantivo)' },
    { kana: 'その', kanji: null, furigana: null, romaji: 'sono', meaning: 'Esse / Essa (+ substantivo)' },
    { kana: 'あの', kanji: null, furigana: null, romaji: 'ano', meaning: 'Aquele / Aquela (+ substantivo)' },

    // === Mídia e Tecnologia ===
    { kana: 'ほん', kanji: '本', furigana: [{ position: 0, reading: 'ほん' }], romaji: 'hon', meaning: 'Livro' },
    { kana: 'じしょ', kanji: '辞書', furigana: [{ position: 0, reading: 'じ' }, { position: 1, reading: 'しょ' }], romaji: 'jisho', meaning: 'Dicionário' },
    { kana: 'しんぶん', kanji: '新聞', furigana: [{ position: 0, reading: 'しん' }, { position: 1, reading: 'ぶん' }], romaji: 'shinbun', meaning: 'Jornal' },
    { kana: 'ペン', kanji: null, furigana: null, romaji: 'pen', meaning: 'Caneta' },
    { kana: 'テレビ', kanji: null, furigana: null, romaji: 'terebi', meaning: 'Televisão' },
    { kana: 'ラジオ', kanji: null, furigana: null, romaji: 'rajio', meaning: 'Rádio' },
    { kana: 'えいが', kanji: '映画', furigana: [{ position: 0, reading: 'えい' }, { position: 1, reading: 'が' }], romaji: 'eiga', meaning: 'Filme' },
    { kana: 'ビデオ', kanji: null, furigana: null, romaji: 'bideo', meaning: 'Vídeo' },
    { kana: 'おんがく', kanji: '音楽', furigana: [{ position: 0, reading: 'おん' }, { position: 1, reading: 'がく' }], romaji: 'ongaku', meaning: 'Música' },
    { kana: 'ニュース', kanji: null, furigana: null, romaji: 'nyuusu', meaning: 'Notícias' },
    { kana: 'パソコン', kanji: null, furigana: null, romaji: 'pasokon', meaning: 'Computador pessoal (PC)' },
    { kana: 'でんわ', kanji: '電話', furigana: [{ position: 0, reading: 'でん' }, { position: 1, reading: 'わ' }], romaji: 'denwa', meaning: 'Telefone' },
    { kana: 'けいたいでんわ', kanji: '携帯電話', furigana: [{ position: 0, reading: 'けい' }, { position: 1, reading: 'たい' }, { position: 2, reading: 'でん' }, { position: 3, reading: 'わ' }], romaji: 'keitaidenwa', meaning: 'Telefone celular' },
    { kana: 'スマホ', kanji: null, furigana: null, romaji: 'sumaho', meaning: 'Smartphone (abreviação)' },
    { kana: 'メール', kanji: null, furigana: null, romaji: 'meeru', meaning: 'E-mail' },
    { kana: 'カメラ', kanji: null, furigana: null, romaji: 'kamera', meaning: 'Câmera' },
    { kana: 'インターネット', kanji: null, furigana: null, romaji: 'intaanetto', meaning: 'Internet' },
    { kana: 'でんしレンジ', kanji: '電子レンジ', furigana: [{ position: 0, reading: 'でん' }, { position: 1, reading: 'し' }], romaji: 'denshi renji', meaning: 'Forno de micro-ondas' },

    // === Roupas ===
    { kana: 'ふく', kanji: '服', furigana: [{ position: 0, reading: 'ふく' }], romaji: 'fuku', meaning: 'Roupas' },
    { kana: 'シャツ', kanji: null, furigana: null, romaji: 'shatsu', meaning: 'Camisa' },
    { kana: 'ズボン', kanji: null, furigana: null, romaji: 'zubon', meaning: 'Calças' },
    { kana: 'スカート', kanji: null, furigana: null, romaji: 'sukaato', meaning: 'Saia' },
    { kana: 'ぼうし', kanji: '帽子', furigana: [{ position: 0, reading: 'ぼう' }, { position: 1, reading: 'し' }], romaji: 'boushi', meaning: 'Chapéu / Boné' },
    { kana: 'くつした', kanji: '靴下', furigana: [{ position: 0, reading: 'くつ' }, { position: 1, reading: 'した' }], romaji: 'kutsushita', meaning: 'Meias' },

    // === Transporte ===
    { kana: 'くるま', kanji: '車', furigana: [{ position: 0, reading: 'くるま' }], romaji: 'kuruma', meaning: 'Carro' },
    { kana: 'でんしゃ', kanji: '電車', furigana: [{ position: 0, reading: 'でん' }, { position: 1, reading: 'しゃ' }], romaji: 'densha', meaning: 'Trem elétrico' },
    { kana: 'ちかてつ', kanji: '地下鉄', furigana: [{ position: 0, reading: 'ち' }, { position: 1, reading: 'か' }, { position: 2, reading: 'てつ' }], romaji: 'chikatetsu', meaning: 'Metrô' },
    { kana: 'バス', kanji: null, furigana: null, romaji: 'basu', meaning: 'Ônibus' },
    { kana: 'タクシー', kanji: null, furigana: null, romaji: 'takushii', meaning: 'Táxi' },
    { kana: 'ひこうき', kanji: '飛行機', furigana: [{ position: 0, reading: 'ひ' }, { position: 1, reading: 'こう' }, { position: 2, reading: 'き' }], romaji: 'hikouki', meaning: 'Avião' },
    { kana: 'ふね', kanji: '船', furigana: [{ position: 0, reading: 'ふね' }], romaji: 'fune', meaning: 'Navio / Barco' },
    { kana: 'じてんしゃ', kanji: '自転車', furigana: [{ position: 0, reading: 'じ' }, { position: 1, reading: 'てん' }, { position: 2, reading: 'しゃ' }], romaji: 'jitensha', meaning: 'Bicicleta' },

    // === Corpo ===
    { kana: 'からだ', kanji: '体', furigana: [{ position: 0, reading: 'からだ' }], romaji: 'karada', meaning: 'Corpo' },
    { kana: 'あたま', kanji: '頭', furigana: [{ position: 0, reading: 'あたま' }], romaji: 'atama', meaning: 'Cabeça' },
    { kana: 'かみ', kanji: '髪', furigana: [{ position: 0, reading: 'かみ' }], romaji: 'kami', meaning: 'Cabelo' },
    { kana: 'かお', kanji: '顔', furigana: [{ position: 0, reading: 'かお' }], romaji: 'kao', meaning: 'Rosto' },
    { kana: 'め', kanji: '目', furigana: [{ position: 0, reading: 'め' }], romaji: 'me', meaning: 'Olho' },
    { kana: 'みみ', kanji: '耳', furigana: [{ position: 0, reading: 'みみ' }], romaji: 'mimi', meaning: 'Orelha' },
    { kana: 'はな', kanji: '鼻', furigana: [{ position: 0, reading: 'はな' }], romaji: 'hana', meaning: 'Nariz' },
    { kana: 'くち', kanji: '口', furigana: [{ position: 0, reading: 'くち' }], romaji: 'kuchi', meaning: 'Boca' },
    { kana: 'は', kanji: '歯', furigana: [{ position: 0, reading: 'は' }], romaji: 'ha', meaning: 'Dente' },
    { kana: 'て', kanji: '手', furigana: [{ position: 0, reading: 'て' }], romaji: 'te', meaning: 'Mão / Braço' },
    { kana: 'あし', kanji: '足', furigana: [{ position: 0, reading: 'あし' }], romaji: 'ashi', meaning: 'Pé / Perna' },
    { kana: 'おなか', kanji: 'お腹', furigana: [{ position: 1, reading: 'なか' }], romaji: 'onaka', meaning: 'Barriga / Estômago' },

    // === Animais ===
    { kana: 'どうぶつ', kanji: '動物', furigana: [{ position: 0, reading: 'どう' }, { position: 1, reading: 'ぶつ' }], romaji: 'doubutsu', meaning: 'Animal' },
    { kana: 'いぬ', kanji: '犬', furigana: [{ position: 0, reading: 'いぬ' }], romaji: 'inu', meaning: 'Cachorro' },
    { kana: 'ねこ', kanji: '猫', furigana: [{ position: 0, reading: 'ねこ' }], romaji: 'neko', meaning: 'Gato' },
    { kana: 'とり', kanji: '鳥', furigana: [{ position: 0, reading: 'とり' }], romaji: 'tori', meaning: 'Pássaro' },
    { kana: 'うさぎ', kanji: '兎', furigana: [{ position: 0, reading: 'うさぎ' }], romaji: 'usagi', meaning: 'Coelho' },
    { kana: 'うま', kanji: '馬', furigana: [{ position: 0, reading: 'うま' }], romaji: 'uma', meaning: 'Cavalo' },
    { kana: 'ぶた', kanji: '豚', furigana: [{ position: 0, reading: 'ぶた' }], romaji: 'buta', meaning: 'Porco' },
    { kana: 'うし', kanji: '牛', furigana: [{ position: 0, reading: 'うし' }], romaji: 'ushi', meaning: 'Vaca / Boi' },
    { kana: 'ひつじ', kanji: '羊', furigana: [{ position: 0, reading: 'ひつじ' }], romaji: 'hitsuji', meaning: 'Ovelha' },
    { kana: 'さる', kanji: '猿', furigana: [{ position: 0, reading: 'さる' }], romaji: 'saru', meaning: 'Macaco' },
    { kana: 'ねずみ', kanji: '鼠', furigana: [{ position: 0, reading: 'ねずみ' }], romaji: 'nezumi', meaning: 'Rato / Camundongo' },
    { kana: 'とら', kanji: '虎', furigana: [{ position: 0, reading: 'とら' }], romaji: 'tora', meaning: 'Tigre' },
    { kana: 'ぞう', kanji: '象', furigana: [{ position: 0, reading: 'ぞう' }], romaji: 'zou', meaning: 'Elefante' },
    { kana: 'パンダ', kanji: null, furigana: null, romaji: 'panda', meaning: 'Panda' },
    { kana: 'ライオン', kanji: null, furigana: null, romaji: 'raion', meaning: 'Leão' },

    // === Hobbies e Interesses ===
    { kana: 'しゅみ', kanji: '趣味', furigana: [{ position: 0, reading: 'しゅ' }, { position: 1, reading: 'み' }], romaji: 'shumi', meaning: 'Hobby / Passatempo' },
    { kana: 'スポーツ', kanji: null, furigana: null, romaji: 'supootsu', meaning: 'Esportes' },
    { kana: 'どくしょ', kanji: '読書', furigana: [{ position: 0, reading: 'どく' }, { position: 1, reading: 'しょ' }], romaji: 'dokusho', meaning: 'Leitura' },
    { kana: 'え', kanji: '絵', furigana: [{ position: 0, reading: 'え' }], romaji: 'e', meaning: 'Pintura / Desenho' },
    { kana: 'りょこう', kanji: '旅行', furigana: [{ position: 0, reading: 'りょ' }, { position: 1, reading: 'こう' }], romaji: 'ryokou', meaning: 'Viagem' },

    // === Materiais Escolares ===
    { kana: 'きょうかしょ', kanji: '教科書', furigana: [{ position: 0, reading: 'きょう' }, { position: 1, reading: 'か' }, { position: 2, reading: 'しょ' }], romaji: 'kyoukasho', meaning: 'Livro didático' },
    { kana: 'ノート', kanji: null, furigana: null, romaji: 'nooto', meaning: 'Caderno' },
    { kana: 'えんぴつ', kanji: '鉛筆', furigana: [{ position: 0, reading: 'えん' }, { position: 1, reading: 'ぴつ' }], romaji: 'enpitsu', meaning: 'Lápis' },
    { kana: 'けしゴム', kanji: '消しゴム', furigana: [{ position: 0, reading: 'け' }], romaji: 'keshigomu', meaning: 'Borracha' },
    { kana: 'しゅくだい', kanji: '宿題', furigana: [{ position: 0, reading: 'しゅく' }, { position: 1, reading: 'だい' }], romaji: 'shukudai', meaning: 'Lição de casa' },

    // === Direções e Posições ===
    { kana: 'みぎ', kanji: '右', furigana: [{ position: 0, reading: 'みぎ' }], romaji: 'migi', meaning: 'Direita' },
    { kana: 'ひだり', kanji: '左', furigana: [{ position: 0, reading: 'ひだり' }], romaji: 'hidari', meaning: 'Esquerda' },
    { kana: 'うえ', kanji: '上', furigana: [{ position: 0, reading: 'うえ' }], romaji: 'ue', meaning: 'Em cima / Acima' },
    { kana: 'した', kanji: '下', furigana: [{ position: 0, reading: 'した' }], romaji: 'shita', meaning: 'Embaixo / Abaixo' },
    { kana: 'まえ', kanji: '前', furigana: [{ position: 0, reading: 'まえ' }], romaji: 'mae', meaning: 'Em frente / Antes' },
    { kana: 'うしろ', kanji: '後ろ', furigana: [{ position: 0, reading: 'うし' }], romaji: 'ushiro', meaning: 'Atrás' },
    { kana: 'なか', kanji: '中', furigana: [{ position: 0, reading: 'なか' }], romaji: 'naka', meaning: 'Dentro' },
    { kana: 'そと', kanji: '外', furigana: [{ position: 0, reading: 'そと' }], romaji: 'soto', meaning: 'Fora' },
    { kana: 'となり', kanji: '隣', furigana: [{ position: 0, reading: 'となり' }], romaji: 'tonari', meaning: 'Ao lado' },

    // === Partículas Essenciais ===
    { kana: 'は', kanji: null, furigana: null, romaji: 'wa', meaning: 'Partícula de tópico (indica sobre o que se fala)' },
    { kana: 'が', kanji: null, furigana: null, romaji: 'ga', meaning: 'Partícula de sujeito (identifica quem/o que faz a ação)' },
    { kana: 'を', kanji: null, furigana: null, romaji: 'o', meaning: 'Partícula de objeto direto (indica o que sofre a ação)' },
    { kana: 'に', kanji: null, furigana: null, romaji: 'ni', meaning: 'Partícula de lugar/tempo (indica destino, localização, momento)' },
    { kana: 'へ', kanji: null, furigana: null, romaji: 'e', meaning: 'Partícula de direção (indica a direção do movimento)' },
    { kana: 'で', kanji: null, furigana: null, romaji: 'de', meaning: 'Partícula de lugar/meio (indica onde a ação ocorre ou o meio)' },
    { kana: 'と', kanji: null, furigana: null, romaji: 'to', meaning: 'Partícula de companhia/lista ("e", "com")' },
    { kana: 'も', kanji: null, furigana: null, romaji: 'mo', meaning: 'Partícula de inclusão ("também")' },
    { kana: 'の', kanji: null, furigana: null, romaji: 'no', meaning: 'Partícula de posse (indica posse ou relação entre substantivos)' },
    { kana: 'か', kanji: null, furigana: null, romaji: 'ka', meaning: 'Partícula de interrogação (transforma uma frase em pergunta)' },

    // === Verbos Comuns ===
    { kana: 'ある', kanji: null, furigana: null, romaji: 'aru', meaning: 'Haver / Ter / Estar (coisas inanimadas, informal)' },
    { kana: 'あります', kanji: 'あります', furigana: null, romaji: 'arimasu', meaning: 'Haver / Ter / Estar (coisas inanimadas, formal)' },
    { kana: 'いる', kanji: null, furigana: null, romaji: 'iru', meaning: 'Haver / Ter / Estar (seres vivos, informal)' },
    { kana: 'います', kanji: 'います', furigana: null, romaji: 'imasu', meaning: 'Haver / Ter / Estar (seres vivos, formal)' },
    { kana: 'いく', kanji: '行く', furigana: [{ position: 0, reading: 'い' }], romaji: 'iku', meaning: 'Ir (informal)' },
    { kana: 'いきます', kanji: '行きます', furigana: [{ position: 0, reading: 'い' }], romaji: 'ikimasu', meaning: 'Ir (formal)' },
    { kana: 'くる', kanji: '来る', furigana: [{ position: 0, reading: 'く' }], romaji: 'kuru', meaning: 'Vir (informal)' },
    { kana: 'きます', kanji: '来ます', furigana: [{ position: 0, reading: 'き' }], romaji: 'kimasu', meaning: 'Vir (formal)' },
    { kana: 'かえる', kanji: '帰る', furigana: [{ position: 0, reading: 'かえ' }], romaji: 'kaeru', meaning: 'Voltar / Retornar (informal)' },
    { kana: 'かえります', kanji: '帰ります', furigana: [{ position: 0, reading: 'かえ' }], romaji: 'kaerimasu', meaning: 'Voltar / Retornar (formal)' },
    { kana: 'たべる', kanji: '食べる', furigana: [{ position: 0, reading: 'た' }], romaji: 'taberu', meaning: 'Comer (informal)' },
    { kana: 'たべます', kanji: '食べます', furigana: [{ position: 0, reading: 'た' }], romaji: 'tabemasu', meaning: 'Comer (formal)' },
    { kana: 'のむ', kanji: '飲む', furigana: [{ position: 0, reading: 'の' }], romaji: 'nomu', meaning: 'Beber (informal)' },
    { kana: 'のみます', kanji: '飲みます', furigana: [{ position: 0, reading: 'の' }], romaji: 'nomimasu', meaning: 'Beber (formal)' },
    { kana: 'みる', kanji: '見る', furigana: [{ position: 0, reading: 'み' }], romaji: 'miru', meaning: 'Ver / Assistir (informal)' },
    { kana: 'みます', kanji: '見ます', furigana: [{ position: 0, reading: 'み' }], romaji: 'mimasu', meaning: 'Ver / Assistir (formal)' },
    { kana: 'きく', kanji: '聞く', furigana: [{ position: 0, reading: 'き' }], romaji: 'kiku', meaning: 'Ouvir / Perguntar (informal)' },
    { kana: 'ききます', kanji: '聞きます', furigana: [{ position: 0, reading: 'き' }], romaji: 'kikimasu', meaning: 'Ouvir / Perguntar (formal)' },
    { kana: 'よむ', kanji: '読む', furigana: [{ position: 0, reading: 'よ' }], romaji: 'yomu', meaning: 'Ler (informal)' },
    { kana: 'よみます', kanji: '読みます', furigana: [{ position: 0, reading: 'よ' }], romaji: 'yomimasu', meaning: 'Ler (formal)' },
    { kana: 'かく', kanji: '書く', furigana: [{ position: 0, reading: 'か' }], romaji: 'kaku', meaning: 'Escrever / Desenhar (informal)' },
    { kana: 'かきます', kanji: '書きます', furigana: [{ position: 0, reading: 'か' }], romaji: 'kakimasu', meaning: 'Escrever / Desenhar (formal)' },
    { kana: 'かう', kanji: '買う', furigana: [{ position: 0, reading: 'か' }], romaji: 'kau', meaning: 'Comprar (informal)' },
    { kana: 'かいます', kanji: '買います', furigana: [{ position: 0, reading: 'か' }], romaji: 'kaimasu', meaning: 'Comprar (formal)' },
    { kana: 'うる', kanji: '売る', furigana: [{ position: 0, reading: 'う' }], romaji: 'uru', meaning: 'Vender (informal)' },
    { kana: 'うります', kanji: '売ります', furigana: [{ position: 0, reading: 'う' }], romaji: 'urimasu', meaning: 'Vender (formal)' },
    { kana: 'する', kanji: null, furigana: null, romaji: 'suru', meaning: 'Fazer (informal)' },
    { kana: 'します', kanji: null, furigana: null, romaji: 'shimasu', meaning: 'Fazer (formal)' },
    { kana: 'べんきょうする', kanji: '勉強する', furigana: [{ position: 0, reading: 'べん' }, { position: 1, reading: 'きょう' }], romaji: 'benkyou suru', meaning: 'Estudar (informal)' },
    { kana: 'べんきょうします', kanji: '勉強します', furigana: [{ position: 0, reading: 'べん' }, { position: 1, reading: 'きょう' }], romaji: 'benkyou shimasu', meaning: 'Estudar (formal)' },
    { kana: 'つくる', kanji: '作る', furigana: [{ position: 0, reading: 'つく' }], romaji: 'tsukuru', meaning: 'Fazer / Criar (informal)' },
    { kana: 'つくります', kanji: '作ります', furigana: [{ position: 0, reading: 'つく' }], romaji: 'tsukurimasu', meaning: 'Fazer / Criar (formal)' },
    { kana: 'もつ', kanji: '持つ', furigana: [{ position: 0, reading: 'も' }], romaji: 'motsu', meaning: 'Segurar / Carregar (informal)' },
    { kana: 'もちます', kanji: '持ちます', furigana: [{ position: 0, reading: 'も' }], romaji: 'mochimasu', meaning: 'Segurar / Carregar (formal)' },
    { kana: 'つかう', kanji: '使う', furigana: [{ position: 0, reading: 'つか' }], romaji: 'tsukau', meaning: 'Usar (informal)' },
    { kana: 'つかいます', kanji: '使います', furigana: [{ position: 0, reading: 'つか' }], romaji: 'tsukaimasu', meaning: 'Usar (formal)' },
    { kana: 'すわる', kanji: '座る', furigana: [{ position: 0, reading: 'すわ' }], romaji: 'suwaru', meaning: 'Sentar-se (informal)' },
    { kana: 'すわります', kanji: '座ります', furigana: [{ position: 0, reading: 'すわ' }], romaji: 'suwarimasu', meaning: 'Sentar-se (formal)' },
    { kana: 'たつ', kanji: '立つ', furigana: [{ position: 0, reading: 'た' }], romaji: 'tatsu', meaning: 'Ficar de pé (informal)' },
    { kana: 'たちます', kanji: '立ちます', furigana: [{ position: 0, reading: 'た' }], romaji: 'tachimasu', meaning: 'Ficar de pé (formal)' },
    { kana: 'はいる', kanji: '入る', furigana: [{ position: 0, reading: 'はい' }], romaji: 'hairu', meaning: 'Entrar (informal)' },
    { kana: 'はいります', kanji: '入ります', furigana: [{ position: 0, reading: 'はい' }], romaji: 'hairimasu', meaning: 'Entrar (formal)' },
    { kana: 'でる', kanji: '出る', furigana: [{ position: 0, reading: 'で' }], romaji: 'deru', meaning: 'Sair (informal)' },
    { kana: 'でます', kanji: '出ます', furigana: [{ position: 0, reading: 'で' }], romaji: 'demasu', meaning: 'Sair (formal)' },
    { kana: 'あける', kanji: '開ける', furigana: [{ position: 0, reading: 'あ' }], romaji: 'akeru', meaning: 'Abrir (informal)' },
    { kana: 'あけます', kanji: '開けます', furigana: [{ position: 0, reading: 'あ' }], romaji: 'akemasu', meaning: 'Abrir (formal)' },
    { kana: 'しめる', kanji: '閉める', furigana: [{ position: 0, reading: 'し' }], romaji: 'shimeru', meaning: 'Fechar (informal)' },
    { kana: 'しめます', kanji: '閉めます', furigana: [{ position: 0, reading: 'し' }], romaji: 'shimemasu', meaning: 'Fechar (formal)' },
    { kana: 'わかる', kanji: '分かる', furigana: [{ position: 0, reading: 'わ' }], romaji: 'wakaru', meaning: 'Entender (informal)' },
    { kana: 'わかります', kanji: '分かります', furigana: [{ position: 0, reading: 'わ' }], romaji: 'wakarimasu', meaning: 'Entender (formal)' },
    { kana: 'しる', kanji: '知る', furigana: [{ position: 0, reading: 'し' }], romaji: 'shiru', meaning: 'Saber / Conhecer (informal)' },
    { kana: 'しります', kanji: '知ります', furigana: [{ position: 0, reading: 'し' }], romaji: 'shirimasu', meaning: 'Saber / Conhecer (formal)' },
    { kana: 'わすれる', kanji: '忘れる', furigana: [{ position: 0, reading: 'わす' }], romaji: 'wasureru', meaning: 'Esquecer (informal)' },
    { kana: 'わすれます', kanji: '忘れます', furigana: [{ position: 0, reading: 'わす' }], romaji: 'wasuremasu', meaning: 'Esquecer (formal)' },
    { kana: 'ならう', kanji: '習う', furigana: [{ position: 0, reading: 'なら' }], romaji: 'narau', meaning: 'Aprender (informal)' },
    { kana: 'ならいます', kanji: '習います', furigana: [{ position: 0, reading: 'なら' }], romaji: 'naraimasu', meaning: 'Aprender (formal)' },
    { kana: 'おしえる', kanji: '教える', furigana: [{ position: 0, reading: 'おし' }], romaji: 'oshieru', meaning: 'Ensinar (informal)' },
    { kana: 'おしえます', kanji: '教えます', furigana: [{ position: 0, reading: 'おし' }], romaji: 'oshiemasu', meaning: 'Ensinar (formal)' },
    { kana: 'まつ', kanji: '待つ', furigana: [{ position: 0, reading: 'ま' }], romaji: 'matsu', meaning: 'Esperar (informal)' },
    { kana: 'まちます', kanji: '待ちます', furigana: [{ position: 0, reading: 'ま' }], romaji: 'machimasu', meaning: 'Esperar (formal)' },
    { kana: 'あう', kanji: '会う', furigana: [{ position: 0, reading: 'あ' }], romaji: 'au', meaning: 'Encontrar-se (informal)' },
    { kana: 'あいます', kanji: '会います', furigana: [{ position: 0, reading: 'あ' }], romaji: 'aimasu', meaning: 'Encontrar-se (formal)' },
    { kana: 'ねる', kanji: '寝る', furigana: [{ position: 0, reading: 'ね' }], romaji: 'neru', meaning: 'Dormir (informal)' },
    { kana: 'ねます', kanji: '寝ます', furigana: [{ position: 0, reading: 'ね' }], romaji: 'nemasu', meaning: 'Dormir (formal)' },
    { kana: 'おきる', kanji: '起きる', furigana: [{ position: 0, reading: 'お' }], romaji: 'okiru', meaning: 'Acordar (informal)' },
    { kana: 'おきます', kanji: '起きます', furigana: [{ position: 0, reading: 'お' }], romaji: 'okimasu', meaning: 'Acordar (formal)' },
    { kana: 'はなす', kanji: '話す', furigana: [{ position: 0, reading: 'はな' }], romaji: 'hanasu', meaning: 'Falar (informal)' },
    { kana: 'はなします', kanji: '話します', furigana: [{ position: 0, reading: 'はな' }], romaji: 'hanashimasu', meaning: 'Falar (formal)' },
    { kana: 'やすむ', kanji: '休む', furigana: [{ position: 0, reading: 'やす' }], romaji: 'yasumu', meaning: 'Descansar / Faltar (informal)' },
    { kana: 'やすみます', kanji: '休みます', furigana: [{ position: 0, reading: 'やす' }], romaji: 'yasumimasu', meaning: 'Descansar / Faltar (formal)' },
    { kana: 'しんぱいする', kanji: '心配する', furigana: [{ position: 0, reading: 'しん' }, { position: 1, reading: 'ぱい' }], romaji: 'shinpai suru', meaning: 'Preocupar-se (informal)' },
    { kana: 'しんぱいします', kanji: '心配します', furigana: [{ position: 0, reading: 'しん' }, { position: 1, reading: 'ぱい' }], romaji: 'shinpai shimasu', meaning: 'Preocupar-se (formal)' },
    { kana: 'おこる', kanji: '怒る', furigana: [{ position: 0, reading: 'おこ' }], romaji: 'okoru', meaning: 'Ficar bravo / Zangar-se (informal)' },
    { kana: 'おこります', kanji: '怒ります', furigana: [{ position: 0, reading: 'おこ' }], romaji: 'okorimasu', meaning: 'Ficar bravo / Zangar-se (formal)' },

	// === Adjetivos Comuns ===
	{ kana: 'おおきい', kanji: '大きい', furigana: [{ position: 0, reading: 'おお' }], romaji: 'ookii', meaning: 'Grande' },
	{ kana: 'ちいさい', kanji: '小さい', furigana: [{ position: 0, reading: 'ちい' }], romaji: 'chiisai', meaning: 'Pequeno' },
	{ kana: 'あたらしい', kanji: '新しい', furigana: [{ position: 0, reading: 'あたら' }], romaji: 'atarashii', meaning: 'Novo' },
	{ kana: 'ふるい', kanji: '古い', furigana: [{ position: 0, reading: 'ふる' }], romaji: 'furui', meaning: 'Velho (para objetos)' },
	{ kana: 'いい', kanji: '良い', furigana: [{ position: 0, reading: 'い' }], romaji: 'ii', meaning: 'Bom' },
	{ kana: 'わるい', kanji: '悪い', furigana: [{ position: 0, reading: 'わる' }], romaji: 'warui', meaning: 'Mau / Ruim' },
	{ kana: 'たかい', kanji: '高い', furigana: [{ position: 0, reading: 'たか' }], romaji: 'takai', meaning: 'Alto / Caro' },
	{ kana: 'ひくい', kanji: '低い', furigana: [{ position: 0, reading: 'ひく' }], romaji: 'hikui', meaning: 'Baixo' },
	{ kana: 'やすい', kanji: '安い', furigana: [{ position: 0, reading: 'やす' }], romaji: 'yasui', meaning: 'Barato' },
	{ kana: 'ながい', kanji: '長い', furigana: [{ position: 0, reading: 'なが' }], romaji: 'nagai', meaning: 'Longo' },
	{ kana: 'みじかい', kanji: '短い', furigana: [{ position: 0, reading: 'みじか' }], romaji: 'mijikai', meaning: 'Curto' },
	{ kana: 'おもい', kanji: '重い', furigana: [{ position: 0, reading: 'おも' }], romaji: 'omoi', meaning: 'Pesado' },
	{ kana: 'かるい', kanji: '軽い', furigana: [{ position: 0, reading: 'かる' }], romaji: 'karui', meaning: 'Leve' },
	{ kana: 'ひろい', kanji: '広い', furigana: [{ position: 0, reading: 'ひろ' }], romaji: 'hiroi', meaning: 'Amplo / Espaçoso' },
	{ kana: 'せまい', kanji: '狭い', furigana: [{ position: 0, reading: 'せま' }], romaji: 'semai', meaning: 'Estreito / Apertado' },
	{ kana: 'あかるい', kanji: '明るい', furigana: [{ position: 0, reading: 'あか' }], romaji: 'akarui', meaning: 'Claro / Iluminado' },
	{ kana: 'くらい', kanji: '暗い', furigana: [{ position: 0, reading: 'くら' }], romaji: 'kurai', meaning: 'Escuro' },
	{ kana: 'はやい', kanji: '速い', furigana: [{ position: 0, reading: 'はや' }], romaji: 'hayai', meaning: 'Rápido' },
	{ kana: 'おそい', kanji: '遅い', furigana: [{ position: 0, reading: 'おそ' }], romaji: 'osoi', meaning: 'Lento / Atrasado' },
	{ kana: 'ちかい', kanji: '近い', furigana: [{ position: 0, reading: 'ちか' }], romaji: 'chikai', meaning: 'Perto' },
	{ kana: 'とおい', kanji: '遠い', furigana: [{ position: 0, reading: 'とお' }], romaji: 'tooi', meaning: 'Longe' },
	{ kana: 'おいしい', kanji: '美味しい', furigana: [{ position: 0, reading: 'おい' }], romaji: 'oishii', meaning: 'Gostoso / Delicioso' },
	{ kana: 'まずい', kanji: null, furigana: null, romaji: 'mazui', meaning: 'Ruim (sabor)' },
	{ kana: 'たのしい', kanji: '楽しい', furigana: [{ position: 0, reading: 'たの' }], romaji: 'tanoshii', meaning: 'Divertido' },
	{ kana: 'おもしろい', kanji: '面白い', furigana: [{ position: 0, reading: 'おも' }, { position: 1, reading: 'しろ' }], romaji: 'omoshiroi', meaning: 'Interessante / Engraçado' },
	{ kana: 'つまらない', kanji: null, furigana: null, romaji: 'tsumaranai', meaning: 'Chato / Entediante' },
	{ kana: 'すばらしい', kanji: '素晴らしい', furigana: [{ position: 0, reading: 'す' }, { position: 1, reading: 'ば' }], romaji: 'subarashii', meaning: 'Maravilhoso / Esplêndido' },
	{ kana: 'むずかしい', kanji: '難しい', furigana: [{ position: 0, reading: 'むずか' }], romaji: 'muzukashii', meaning: 'Difícil' },
	{ kana: 'やさしい', kanji: '易しい', furigana: [{ position: 0, reading: 'やさ' }], romaji: 'yasashii', meaning: 'Fácil' },
	{ kana: 'やさしい', kanji: '優しい', furigana: [{ position: 0, reading: 'やさ' }], romaji: 'yasashii', meaning: 'Gentil / Amável' },
	{ kana: 'あつい', kanji: '暑い', furigana: [{ position: 0, reading: 'あつ' }], romaji: 'atsui', meaning: 'Quente (clima)' },
	{ kana: 'さむい', kanji: '寒い', furigana: [{ position: 0, reading: 'さむ' }], romaji: 'samui', meaning: 'Frio (clima)' },
	{ kana: 'つめたい', kanji: '冷たい', furigana: [{ position: 0, reading: 'つめ' }], romaji: 'tsumetai', meaning: 'Frio (objetos/toque)' },
	{ kana: 'あつい', kanji: '熱い', furigana: [{ position: 0, reading: 'あつ' }], romaji: 'atsui', meaning: 'Quente (objetos/toque)' },
	{ kana: 'きれい', kanji: '綺麗', furigana: [{ position: 0, reading: 'き' }, { position: 1, reading: 'れい' }], romaji: 'kirei', meaning: 'Bonito / Limpo' },

    // === Sentimentos/Estados e Condições ===
    { kana: 'うれしい', kanji: '嬉しい', furigana: [{ position: 0, reading: 'うれ' }], romaji: 'ureshii', meaning: 'Feliz / Contente' },
    { kana: 'かなしい', kanji: '悲しい', furigana: [{ position: 0, reading: 'かな' }], romaji: 'kanashii', meaning: 'Triste' },
    { kana: 'こわい', kanji: '怖い', furigana: [{ position: 0, reading: 'こわ' }], romaji: 'kowai', meaning: 'Assustador / Com medo' },
    { kana: 'さびしい', kanji: '寂しい', furigana: [{ position: 0, reading: 'さび' }], romaji: 'sabishii', meaning: 'Sozinho / Solitário' },
    { kana: 'つかれました', kanji: '疲れました', furigana: [{ position: 0, reading: 'つか' }], romaji: 'tsukaremashita', meaning: 'Estou cansado(a)' },
    { kana: 'ねむい', kanji: '眠い', furigana: [{ position: 0, reading: 'ねむ' }], romaji: 'nemui', meaning: 'Com sono' },
    { kana: 'げんき', kanji: '元気', furigana: [{ position: 0, reading: 'げん' }, { position: 1, reading: 'き' }], romaji: 'genki', meaning: 'Saudável / Enérgico' },
    { kana: 'びょうき', kanji: '病気', furigana: [{ position: 0, reading: 'びょう' }, { position: 1, reading: 'き' }], romaji: 'byouki', meaning: 'Doença / Doente' },
    { kana: 'だいじょうぶ', kanji: '大丈夫', furigana: [{ position: 0, reading: 'だい' }, { position: 1, reading: 'じょう' }, { position: 2, reading: 'ぶ' }], romaji: 'daijoubu', meaning: 'Tudo bem / Ok' },
    { kana: 'すき', kanji: '好き', furigana: [{ position: 0, reading: 'す' }], romaji: 'suki', meaning: 'Gostar / Favorito' },
    { kana: 'きらい', kanji: '嫌い', furigana: [{ position: 0, reading: 'きら' }], romaji: 'kirai', meaning: 'Não gostar / Odiar' },
    { kana: 'いそがしい', kanji: '忙しい', furigana: [{ position: 0, reading: 'いそが' }], romaji: 'isogashii', meaning: 'Ocupado' },
    { kana: 'ひま', kanji: '暇', furigana: [{ position: 0, reading: 'ひま' }], romaji: 'hima', meaning: 'Livre (tempo)' },
    { kana: 'きもちいい', kanji: '気持ちいい', furigana: [{ position: 0, reading: 'き' }, { position: 1, reading: 'も' }, { position: 2, reading: 'ち' }], romaji: 'kimochiii', meaning: 'Agradável / Confortável' },
    { kana: 'じょうず', kanji: '上手', furigana: [{ position: 0, reading: 'じょう' }, { position: 1, reading: 'ず' }], romaji: 'jouzu', meaning: 'Habilidoso / Bom em algo' },
    { kana: 'へた', kanji: '下手', furigana: [{ position: 0, reading: 'へ' }, { position: 1, reading: 'た' }], romaji: 'heta', meaning: 'Inábil / Ruim em algo' },
    { kana: 'べんり', kanji: '便利', furigana: [{ position: 0, 'reading': 'べん' }, { position: 1, 'reading': 'り' }], romaji: 'benri', meaning: 'Conveniente / Prático' },
    { kana: 'ふべん', kanji: '不便', furigana: [{ position: 0, reading: 'ふ' }, { position: 1, reading: 'べん' }], romaji: 'fuben', meaning: 'Inconveniente' },
    { kana: 'しずか', kanji: '静か', furigana: [{ position: 0, reading: 'しず' }], romaji: 'shizuka', meaning: 'Silencioso / Calmo' },
    { kana: 'にぎやか', kanji: '賑やか', furigana: [{ position: 0, reading: 'にぎ' }], romaji: 'nigiyaka', meaning: 'Agitado / Movimentado' },
    { kana: 'しんせつ', kanji: '親切', furigana: [{ position: 0, reading: 'しん' }, { position: 1, reading: 'せつ' }], romaji: 'shinsetsu', meaning: 'Gentil / Amável' },

    // === Perguntas e Advérbios ===
    { kana: 'なに', kanji: '何', furigana: [{ position: 0, reading: 'なに' }], romaji: 'nani', meaning: 'O quê?' },
    { kana: 'なんですか', kanji: '何ですか', furigana: [{ position: 0, reading: 'なん' }], romaji: 'nan desu ka', meaning: 'O que é?' },
    { kana: 'だれ', kanji: '誰', furigana: [{ position: 0, reading: 'だれ' }], romaji: 'dare', meaning: 'Quem?' },
    { kana: 'だれですか', kanji: '誰ですか', furigana: [{ position: 0, reading: 'だれ' }], romaji: 'dare desu ka', meaning: 'Quem é?' },
    { kana: 'いつ', kanji: null, furigana: null, romaji: 'itsu', meaning: 'Quando?' },
    { kana: 'いつですか', kanji: null, furigana: null, romaji: 'itsu desu ka', meaning: 'Quando é?' },
    { kana: 'どこ', kanji: null, furigana: null, romaji: 'doko', meaning: 'Onde?' },
    { kana: 'どこですか', kanji: null, furigana: null, romaji: 'doko desu ka', meaning: 'Onde é?' },
    { kana: 'どうして', kanji: null, furigana: null, romaji: 'doushite', meaning: 'Por quê?' },
    { kana: 'なぜ', kanji: '何故', furigana: [{ position: 0, reading: 'なぜ' }], romaji: 'naze', meaning: 'Por que? (mais formal)' },
    { kana: 'どう', kanji: null, furigana: null, romaji: 'dou', meaning: 'Como?' },
    { kana: 'いくら', kanji: null, furigana: null, romaji: 'ikura', meaning: 'Quanto custa?' },
    { kana: 'いくつ', kanji: 'いくつ', furigana: null, romaji: 'ikutsu', meaning: 'Quantos / Qual idade' },
    { kana: 'どれ', kanji: null, furigana: null, romaji: 'dore', meaning: 'Qual (entre três ou mais)' },
    { kana: 'どの', kanji: null, furigana: null, romaji: 'dono', meaning: 'Qual (seguido de substantivo)' },
    { kana: 'どちら', kanji: null, furigana: null, romaji: 'dochira', meaning: 'Qual / Onde (formal)' },
    { kana: 'どのくらい', kanji: null, furigana: null, romaji: 'dono kurai', meaning: 'Quanto tempo / Quantos' },
    { kana: 'おげんきですか', kanji: 'お元気ですか', furigana: [{ position: 1, reading: 'げん' }, { position: 2, reading: 'き' }], romaji: 'ogenki desu ka', meaning: 'Como você está?' },
    { kana: 'げんきです', kanji: '元気です', furigana: [{ position: 0, reading: 'げん' }, { position: 1, reading: 'き' }], romaji: 'genki desu', meaning: 'Estou bem' },
    { kana: 'とても', kanji: 'とても', furigana: null, romaji: 'totemo', meaning: 'Muito' },
    { kana: 'すこし', kanji: '少し', furigana: [{ position: 0, reading: 'すこ' }], romaji: 'sukoshi', meaning: 'Um pouco' },
    { kana: 'もういちど', kanji: 'もう一度', furigana: [{ position: 2, reading: 'いち' }, { position: 3, reading: 'ど' }], romaji: 'mou ichido', meaning: 'Mais uma vez' },
    { kana: 'ゆっくり', kanji: null, furigana: null, romaji: 'yukkuri', meaning: 'Devagar' },
    { kana: 'いっしょに', kanji: '一緒に', furigana: [{ position: 0, reading: 'いっ' }, { position: 1, reading: 'しょ' }], romaji: 'issho ni', meaning: 'Juntos' },
    { kana: 'たとえば', kanji: '例えば', furigana: [{ position: 0, reading: 'たと' }], romaji: 'tatoeba', meaning: 'Por exemplo' },
    { kana: 'たぶん', kanji: '多分', furigana: [{ position: 0, reading: 'た' }, { position: 1, reading: 'ぶん' }], romaji: 'tabun', meaning: 'Talvez' },
    { kana: 'ほんとうに', kanji: '本当に', furigana: [{ position: 0, reading: 'ほん' }, { position: 1, reading: 'とう' }], romaji: 'hontou ni', meaning: 'Realmente / Sério' },
    { kana: 'ぜんぶ', kanji: '全部', furigana: [{ position: 0, reading: 'ぜん' }, { position: 1, reading: 'ぶ' }], romaji: 'zenbu', meaning: 'Tudo / Total' },

    // === Cores ===
    { kana: 'いろ', kanji: '色', furigana: [{ position: 0, reading: 'いろ' }], romaji: 'iro', meaning: 'Cor' },
    { kana: 'あか', kanji: '赤', furigana: [{ position: 0, reading: 'あか' }], romaji: 'aka', meaning: 'Vermelho' },
    { kana: 'あお', kanji: '青', furigana: [{ position: 0, reading: 'あお' }], romaji: 'ao', meaning: 'Azul' },
    { kana: 'しろ', kanji: '白', furigana: [{ position: 0, reading: 'しろ' }], romaji: 'shiro', meaning: 'Branco' },
    { kana: 'くろ', kanji: '黒', furigana: [{ position: 0, reading: 'くろ' }], romaji: 'kuro', meaning: 'Preto' },
    { kana: 'きいろ', kanji: '黄色', furigana: [{ position: 0, reading: 'きい' }, { position: 1, reading: 'ろ' }], romaji: 'kiiro', meaning: 'Amarelo' },
    { kana: 'みどり', kanji: '緑', furigana: [{ position: 0, reading: 'みどり' }], romaji: 'midori', meaning: 'Verde' },
    { kana: 'ピンク', kanji: null, furigana: null, romaji: 'pinku', meaning: 'Rosa' },
    { kana: 'ちゃいろ', kanji: '茶色', furigana: [{ position: 0, reading: 'ちゃ' }, { position: 1, reading: 'いろ' }], romaji: 'chairo', meaning: 'Marrom' },
    { kana: 'むらさき', kanji: '紫', furigana: [{ position: 0, reading: 'むらさき' }], romaji: 'murasaki', meaning: 'Roxo' },
    { kana: 'はいいろ', kanji: '灰色', furigana: [{ position: 0, reading: 'はい' }, { position: 1, reading: 'いろ' }], romaji: 'haiiro', meaning: 'Cinza' },
    { kana: 'みずいろ', kanji: '水色', furigana: [{ position: 0, reading: 'みず' }, { position: 1, reading: 'いろ' }], romaji: 'mizuiro', meaning: 'Azul claro' },
    { kana: 'オレンジいろ', kanji: 'オレンジ色', furigana: [{ position: 5, reading: 'いろ' }], romaji: 'orenji iro', meaning: 'Cor de laranja' },

    // === Números ===
    { kana: 'いち', kanji: '一', furigana: [{ position: 0, reading: 'いち' }], romaji: 'ichi', meaning: 'Um' },
    { kana: 'に', kanji: '二', furigana: [{ position: 0, reading: 'に' }], romaji: 'ni', meaning: 'Dois' },
    { kana: 'さん', kanji: '三', furigana: [{ position: 0, reading: 'さん' }], romaji: 'san', meaning: 'Três' },
    { kana: 'よん', kanji: '四', furigana: [{ position: 0, reading: 'よん' }], romaji: 'yon', meaning: 'Quatro' },
    { kana: 'ご', kanji: '五', furigana: [{ position: 0, reading: 'ご' }], romaji: 'go', meaning: 'Cinco' },
    { kana: 'ろく', kanji: '六', furigana: [{ position: 0, reading: 'ろく' }], romaji: 'roku', meaning: 'Seis' },
    { kana: 'なな', kanji: '七', furigana: [{ position: 0, reading: 'なな' }], romaji: 'nana', meaning: 'Sete' },
    { kana: 'はち', kanji: '八', furigana: [{ position: 0, reading: 'はち' }], romaji: 'hachi', meaning: 'Oito' },
    { kana: 'きゅう', kanji: '九', furigana: [{ position: 0, reading: 'きゅう' }], romaji: 'kyuu', meaning: 'Nove' },
    { kana: 'じゅう', kanji: '十', furigana: [{ position: 0, reading: 'じゅう' }], romaji: 'juu', meaning: 'Dez' },
    { kana: 'ひゃく', kanji: '百', furigana: [{ position: 0, reading: 'ひゃく' }], romaji: 'hyaku', meaning: 'Cem' },
    { kana: 'せん', kanji: '千', furigana: [{ position: 0, reading: 'せん' }], romaji: 'sen', meaning: 'Mil' },
    { kana: 'まん', kanji: '万', furigana: [{ position: 0, reading: 'まん' }], romaji: 'man', meaning: 'Dez mil' },
    { kana: 'ひとつ', kanji: '一つ', furigana: [{ position: 0, reading: 'ひと' }], romaji: 'hitotsu', meaning: 'Um (contador geral)' },
    { kana: 'ふたつ', kanji: '二つ', furigana: [{ position: 0, reading: 'ふた' }], romaji: 'futatsu', meaning: 'Dois (contador geral)' },
    { kana: 'みっつ', kanji: '三つ', furigana: [{ position: 0, reading: 'みっ' }], romaji: 'mittsu', meaning: 'Três (contador geral)' },
    { kana: 'ひとり', kanji: '一人', furigana: [{ position: 0, reading: 'ひとり' }], romaji: 'hitori', meaning: 'Uma pessoa' },
    { kana: 'ふたり', kanji: '二人', furigana: [{ position: 0, reading: 'ふたり' }], romaji: 'futari', meaning: 'Duas pessoas' },

    // === Trabalho e Estudo ===
    { kana: 'しごと', kanji: '仕事', furigana: [{ position: 0, reading: 'し' }, { position: 1, reading: 'ごと' }], romaji: 'shigoto', meaning: 'Trabalho / Emprego' },
    { kana: 'かいぎ', kanji: '会議', furigana: [{ position: 0, reading: 'かい' }, { position: 1, reading: 'ぎ' }], romaji: 'kaigi', meaning: 'Reunião' },
    { kana: 'じゅぎょう', kanji: '授業', furigana: [{ position: 0, reading: 'じゅ' }, { position: 1, reading: 'ぎょう' }], romaji: 'jugyou', meaning: 'Aula' },
    { kana: 'しけん', kanji: '試験', furigana: [{ position: 0, reading: 'し' }, { position: 1, reading: 'けん' }], romaji: 'shiken', meaning: 'Prova / Exame' },

    // === Conceitos Abstratos e Ideias ===
    { kana: 'みらい', kanji: '未来', furigana: [{ position: 0, reading: 'み' }, { position: 1, reading: 'らい' }], romaji: 'mirai', meaning: 'Futuro' },
    { kana: 'ゆめ', kanji: '夢', furigana: [{ position: 0, reading: 'ゆめ' }], romaji: 'yume', meaning: 'Sonho / Meta' },
    { kana: 'へいわ', kanji: '平和', furigana: [{ position: 0, reading: 'へい' }, { position: 1, reading: 'わ' }], romaji: 'heiwa', meaning: 'Paz' },
    { kana: 'れきし', kanji: '歴史', furigana: [{ position: 0, reading: 'れき' }, { position: 1, reading: 'し' }], romaji: 'rekishi', meaning: 'História' },
    { kana: 'ぶんか', kanji: '文化', furigana: [{ position: 0, reading: 'ぶん' }, { position: 1, reading: 'か' }], romaji: 'bunka', meaning: 'Cultura' },
    { kana: 'もんだい', kanji: '問題', furigana: [{ position: 0, reading: 'もん' }, { position: 1, reading: 'だい' }], romaji: 'mondai', meaning: 'Problema / Questão' },
    { kana: 'こたえ', kanji: '答え', furigana: [{ position: 0, reading: 'こた' }], romaji: 'kotae', meaning: 'Resposta' },

    // === Adjetivos e Expressões Úteis ===
    { kana: 'あぶない', kanji: '危ない', furigana: [{ position: 0, reading: 'あぶ' }], romaji: 'abunai', meaning: 'Perigoso' },
    { kana: 'あんぜん', kanji: '安全', furigana: [{ position: 0, reading: 'あん' }, { position: 1, reading: 'ぜん' }], romaji: 'anzen', meaning: 'Seguro' },
    { kana: 'たいせつ', kanji: '大切', furigana: [{ position: 0, reading: 'たい' }, { position: 1, reading: 'せつ' }], romaji: 'taisetsu', meaning: 'Importante / Precioso' },
    { kana: 'だめ', kanji: '駄目', furigana: [{ position: 0, reading: 'だ' }, { position: 1, reading: 'め' }], romaji: 'dame', meaning: 'Não pode / Ruim / Inútil' },
    { kana: 'つよい', kanji: '強い', furigana: [{ position: 0, reading: 'つよ' }], romaji: 'tsuyoi', meaning: 'Forte' },
    { kana: 'よわい', kanji: '弱い', furigana: [{ position: 0, reading: 'よわ' }], romaji: 'yowai', meaning: 'Fraco' },
    { kana: 'がんばって', kanji: '頑張って', furigana: [{ position: 0, reading: 'がんば' }], romaji: 'ganbatte', meaning: 'Dê o seu melhor! / Força!' },
    { kana: 'やめて', kanji: null, furigana: null, romaji: 'yamete', meaning: 'Pare!' },

    // === Cultura Pop (Anime, Mangá, Videogame) ===
    { kana: 'アニメ', kanji: null, furigana: null, romaji: 'anime', meaning: 'Animação japonesa' },
    { kana: 'マンガ', kanji: '漫画', furigana: [{ position: 0, reading: 'まん' }, { position: 1, reading: 'が' }], romaji: 'manga', meaning: 'Quadrinhos japoneses' },
    { kana: 'オタク', kanji: null, furigana: null, romaji: 'otaku', meaning: 'Fã obcecado (geralmente por anime/mangá)' },
    { kana: 'かわいい', kanji: '可愛い', furigana: [{ position: 0, reading: 'かわい' }], romaji: 'kawaii', meaning: 'Fofo / Adorável' },
    { kana: 'すごい', kanji: '凄い', furigana: [{ position: 0, reading: 'すご' }], romaji: 'sugoi', meaning: 'Incrível / Impressionante' },
    { kana: 'せんぱい', kanji: '先輩', furigana: [{ position: 0, reading: 'せん' }, { position: 1, reading: 'ぱい' }], romaji: 'senpai', meaning: 'Veterano / Superior (em escola, trabalho)' },
    { kana: 'こうはい', kanji: '後輩', furigana: [{ position: 0, reading: 'こう' }, { position: 1, reading: 'はい' }], romaji: 'kouhai', meaning: 'Calouro / Júnior' },
    { kana: 'ばか', kanji: '馬鹿', furigana: [{ position: 0, reading: 'ば' }, { position: 1, reading: 'か' }], romaji: 'baka', meaning: 'Idiota / Tolo (usado como xingamento leve)' },
    { kana: 'なかま', kanji: '仲間', furigana: [{ position: 0, reading: 'なか' }, { position: 1, reading: 'ま' }], romaji: 'nakama', meaning: 'Companheiro / Aliado / Membro do grupo' },
    { kana: 'いせかい', kanji: '異世界', furigana: [{ position: 0, reading: 'い' }, { position: 1, reading: 'せ' }, { position: 2, reading: 'かい' }], romaji: 'isekai', meaning: 'Outro mundo (gênero de anime/mangá)' },
    { kana: 'しょうねん', kanji: '少年', furigana: [{ position: 0, reading: 'しょう' }, { position: 1, reading: 'ねん' }], romaji: 'shounen', meaning: 'Garoto (gênero para o público masculino jovem)' },
    { kana: 'しょうじょ', kanji: '少女', furigana: [{ position: 0, reading: 'しょう' }, { position: 1, reading: 'じょ' }], romaji: 'shoujo', meaning: 'Garota (gênero para o público feminino jovem)' },
    { kana: 'せいゆう', kanji: '声優', furigana: [{ position: 0, reading: 'せい' }, { position: 1, reading: 'ゆう' }], romaji: 'seiyuu', meaning: 'Ator/Atriz de voz' },
    { kana: 'コスプレ', kanji: null, furigana: null, romaji: 'kosupure (cosplay)', meaning: 'Ato de se vestir como um personagem' },
    { kana: 'ガチャ', kanji: null, furigana: null, romaji: 'gacha', meaning: 'Tipo de sorteio/mecânica em jogos' },
    { kana: 'ツンデレ', kanji: null, furigana: null, romaji: 'tsundere', meaning: 'Arquétipo de personagem (frio por fora, amável por dentro)' },
    { kana: 'ヤンデレ', kanji: null, furigana: null, romaji: 'yandere', meaning: 'Arquétipo de personagem (doce que se torna obsessivo e violento)' },
    { kana: 'ちび', kanji: null, furigana: null, romaji: 'chibi', meaning: 'Pequeno / Baixinho (estilo de arte com personagens pequenos)' },
    { kana: 'まほう', kanji: '魔法', furigana: [{ position: 0, reading: 'ま' }, { position: 1, reading: 'ほう' }], romaji: 'mahou', meaning: 'Magia' },
    { kana: 'ゆうしゃ', kanji: '勇者', furigana: [{ position: 0, reading: 'ゆう' }, { position: 1, reading: 'しゃ' }], romaji: 'yuusha', meaning: 'Herói' },
    { kana: 'まおう', kanji: '魔王', furigana: [{ position: 0, reading: 'ま' }, { position: 1, reading: 'おう' }], romaji: 'maou', meaning: 'Rei Demônio' },
    { kana: 'にんじゃ', kanji: '忍者', furigana: [{ position: 0, reading: 'にん' }, { position: 1, reading: 'じゃ' }], romaji: 'ninja', meaning: 'Ninja' },
    { kana: 'さむらい', kanji: '侍', furigana: [{ position: 0, reading: 'さむらい' }], romaji: 'samurai', meaning: 'Samurai' },
    { kana: 'かみ', kanji: '神', furigana: [{ position: 0, reading: 'かみ' }], romaji: 'kami', meaning: 'Deus / Divindade' },
    { kana: 'ようかい', kanji: '妖怪', furigana: [{ position: 0, reading: 'よう' }, { position: 1, reading: 'かい' }], romaji: 'youkai', meaning: 'Demônio / Monstro / Aparição sobrenatural' },
    { kana: 'おに', kanji: '鬼', furigana: [{ position: 0, reading: 'おに' }], romaji: 'oni', meaning: 'Ogro / Demônio (geralmente com chifres)' },
    { kana: 'たたかえ', kanji: '戦え', furigana: [{ position: 0, reading: 'たたか' }], romaji: 'tatakae', meaning: 'Lute! (forma imperativa)' },
    { kana: 'しにがみ', kanji: '死神', furigana: [{ position: 0, reading: 'しに' }, { position: 1, reading: 'がみ' }], romaji: 'shinigami', meaning: 'Deus da morte' },
    { kana: 'フラグ', kanji: null, furigana: null, romaji: 'furagu (flag)', meaning: 'Sinal que indica um evento futuro (ex: "death flag")' },
    { kana: 'ワイフ', kanji: null, furigana: null, romaji: 'waifu', meaning: 'Personagem feminina fictícia pela qual se tem afeição' },
    { kana: 'ハズバンド', kanji: null, furigana: null, romaji: 'hazubando', meaning: 'Personagem masculino fictício pelo qual se tem afeição' },
    { kana: 'ドラゴン', kanji: null, furigana: null, romaji: 'doragon', meaning: 'Dragão' },
    { kana: 'ロボット', kanji: null, furigana: null, romaji: 'robotto', meaning: 'Robô' },
];